[viewer]
    Title = "Go语言博客"
    Description = "Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/327881167"
    Zhihu = "https://www.zhihu.com/people/simple-20-7-18"
    Avatar = "https://p4.music.126.net/zQsuZvhJygPTFTM_FFnqhQ==/109951164139588912.jpg?param=200y200"
    UserName = "admin"
    UserDesc = "长得非常帅的程序员"
[system]
    CdnURL = "/resource"
    QiniuAccessKey = "YtcvYq8Ns7TEYvkvopsBsIcgbYqdCNn_96ri3cdb"
    QiniuSecretKey = "1wbJs1WIJIDQSNs5dbKOMhLDnffJAXQqDlNFtxOo"
    Valine = true
    ValineAppid = "vALhyxWhCaXroMVsOe6jTTBz-gzGzoHsz"
    ValineAppkey = "yq4klKrjjEfVAG7kzH29xvTd"
    ValineServerURL = "https://valhyxwh.lc-cn-n1-shared.com"